title: "cat-oscillator-sync"
description: "cat-oscillator-sync"
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/cat2151/cat-oscillator-sync
plugins:
  - jekyll-sitemap
